// source: contexts/v1/contexts.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.docker.api.protos.context.v1.AciEndpoint', null, global);
goog.exportSymbol('proto.com.docker.api.protos.context.v1.Context', null, global);
goog.exportSymbol('proto.com.docker.api.protos.context.v1.Context.EndpointCase', null, global);
goog.exportSymbol('proto.com.docker.api.protos.context.v1.DockerEndpoint', null, global);
goog.exportSymbol('proto.com.docker.api.protos.context.v1.EcsEndpoint', null, global);
goog.exportSymbol('proto.com.docker.api.protos.context.v1.ListRequest', null, global);
goog.exportSymbol('proto.com.docker.api.protos.context.v1.ListResponse', null, global);
goog.exportSymbol('proto.com.docker.api.protos.context.v1.SetCurrentRequest', null, global);
goog.exportSymbol('proto.com.docker.api.protos.context.v1.SetCurrentResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.context.v1.Context = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.docker.api.protos.context.v1.Context.oneofGroups_);
};
goog.inherits(proto.com.docker.api.protos.context.v1.Context, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.context.v1.Context.displayName = 'proto.com.docker.api.protos.context.v1.Context';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.context.v1.DockerEndpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.context.v1.DockerEndpoint.displayName = 'proto.com.docker.api.protos.context.v1.DockerEndpoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.context.v1.AciEndpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.context.v1.AciEndpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.context.v1.AciEndpoint.displayName = 'proto.com.docker.api.protos.context.v1.AciEndpoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.context.v1.EcsEndpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.context.v1.EcsEndpoint.displayName = 'proto.com.docker.api.protos.context.v1.EcsEndpoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.context.v1.SetCurrentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.context.v1.SetCurrentRequest.displayName = 'proto.com.docker.api.protos.context.v1.SetCurrentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.context.v1.SetCurrentResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.context.v1.SetCurrentResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.context.v1.SetCurrentResponse.displayName = 'proto.com.docker.api.protos.context.v1.SetCurrentResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.context.v1.ListRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.context.v1.ListRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.context.v1.ListRequest.displayName = 'proto.com.docker.api.protos.context.v1.ListRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.context.v1.ListResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.docker.api.protos.context.v1.ListResponse.repeatedFields_, null);
};
goog.inherits(proto.com.docker.api.protos.context.v1.ListResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.context.v1.ListResponse.displayName = 'proto.com.docker.api.protos.context.v1.ListResponse';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.docker.api.protos.context.v1.Context.oneofGroups_ = [[5,6,7]];

/**
 * @enum {number}
 */
proto.com.docker.api.protos.context.v1.Context.EndpointCase = {
  ENDPOINT_NOT_SET: 0,
  DOCKER_ENDPOINT: 5,
  ACI_ENDPOINT: 6,
  ECS_ENDPOINT: 7
};

/**
 * @return {proto.com.docker.api.protos.context.v1.Context.EndpointCase}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.getEndpointCase = function() {
  return /** @type {proto.com.docker.api.protos.context.v1.Context.EndpointCase} */(jspb.Message.computeOneofCase(this, proto.com.docker.api.protos.context.v1.Context.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.context.v1.Context.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.context.v1.Context} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.Context.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    contexttype: jspb.Message.getFieldWithDefault(msg, 2, ""),
    current: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    description: jspb.Message.getFieldWithDefault(msg, 4, ""),
    dockerEndpoint: (f = msg.getDockerEndpoint()) && proto.com.docker.api.protos.context.v1.DockerEndpoint.toObject(includeInstance, f),
    aciEndpoint: (f = msg.getAciEndpoint()) && proto.com.docker.api.protos.context.v1.AciEndpoint.toObject(includeInstance, f),
    ecsEndpoint: (f = msg.getEcsEndpoint()) && proto.com.docker.api.protos.context.v1.EcsEndpoint.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.context.v1.Context}
 */
proto.com.docker.api.protos.context.v1.Context.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.context.v1.Context;
  return proto.com.docker.api.protos.context.v1.Context.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.context.v1.Context} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.context.v1.Context}
 */
proto.com.docker.api.protos.context.v1.Context.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContexttype(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setCurrent(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 5:
      var value = new proto.com.docker.api.protos.context.v1.DockerEndpoint;
      reader.readMessage(value,proto.com.docker.api.protos.context.v1.DockerEndpoint.deserializeBinaryFromReader);
      msg.setDockerEndpoint(value);
      break;
    case 6:
      var value = new proto.com.docker.api.protos.context.v1.AciEndpoint;
      reader.readMessage(value,proto.com.docker.api.protos.context.v1.AciEndpoint.deserializeBinaryFromReader);
      msg.setAciEndpoint(value);
      break;
    case 7:
      var value = new proto.com.docker.api.protos.context.v1.EcsEndpoint;
      reader.readMessage(value,proto.com.docker.api.protos.context.v1.EcsEndpoint.deserializeBinaryFromReader);
      msg.setEcsEndpoint(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.context.v1.Context.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.context.v1.Context} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.Context.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getContexttype();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCurrent();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDockerEndpoint();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.docker.api.protos.context.v1.DockerEndpoint.serializeBinaryToWriter
    );
  }
  f = message.getAciEndpoint();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.com.docker.api.protos.context.v1.AciEndpoint.serializeBinaryToWriter
    );
  }
  f = message.getEcsEndpoint();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.com.docker.api.protos.context.v1.EcsEndpoint.serializeBinaryToWriter
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
 */
proto.com.docker.api.protos.context.v1.Context.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string contextType = 2;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.getContexttype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
 */
proto.com.docker.api.protos.context.v1.Context.prototype.setContexttype = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool current = 3;
 * @return {boolean}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.getCurrent = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
 */
proto.com.docker.api.protos.context.v1.Context.prototype.setCurrent = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional string description = 4;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
 */
proto.com.docker.api.protos.context.v1.Context.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional DockerEndpoint docker_endpoint = 5;
 * @return {?proto.com.docker.api.protos.context.v1.DockerEndpoint}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.getDockerEndpoint = function() {
  return /** @type{?proto.com.docker.api.protos.context.v1.DockerEndpoint} */ (
    jspb.Message.getWrapperField(this, proto.com.docker.api.protos.context.v1.DockerEndpoint, 5));
};


/**
 * @param {?proto.com.docker.api.protos.context.v1.DockerEndpoint|undefined} value
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
*/
proto.com.docker.api.protos.context.v1.Context.prototype.setDockerEndpoint = function(value) {
  return jspb.Message.setOneofWrapperField(this, 5, proto.com.docker.api.protos.context.v1.Context.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
 */
proto.com.docker.api.protos.context.v1.Context.prototype.clearDockerEndpoint = function() {
  return this.setDockerEndpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.hasDockerEndpoint = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional AciEndpoint aci_endpoint = 6;
 * @return {?proto.com.docker.api.protos.context.v1.AciEndpoint}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.getAciEndpoint = function() {
  return /** @type{?proto.com.docker.api.protos.context.v1.AciEndpoint} */ (
    jspb.Message.getWrapperField(this, proto.com.docker.api.protos.context.v1.AciEndpoint, 6));
};


/**
 * @param {?proto.com.docker.api.protos.context.v1.AciEndpoint|undefined} value
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
*/
proto.com.docker.api.protos.context.v1.Context.prototype.setAciEndpoint = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.com.docker.api.protos.context.v1.Context.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
 */
proto.com.docker.api.protos.context.v1.Context.prototype.clearAciEndpoint = function() {
  return this.setAciEndpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.hasAciEndpoint = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional EcsEndpoint ecs_endpoint = 7;
 * @return {?proto.com.docker.api.protos.context.v1.EcsEndpoint}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.getEcsEndpoint = function() {
  return /** @type{?proto.com.docker.api.protos.context.v1.EcsEndpoint} */ (
    jspb.Message.getWrapperField(this, proto.com.docker.api.protos.context.v1.EcsEndpoint, 7));
};


/**
 * @param {?proto.com.docker.api.protos.context.v1.EcsEndpoint|undefined} value
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
*/
proto.com.docker.api.protos.context.v1.Context.prototype.setEcsEndpoint = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.com.docker.api.protos.context.v1.Context.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.com.docker.api.protos.context.v1.Context} returns this
 */
proto.com.docker.api.protos.context.v1.Context.prototype.clearEcsEndpoint = function() {
  return this.setEcsEndpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.com.docker.api.protos.context.v1.Context.prototype.hasEcsEndpoint = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.context.v1.DockerEndpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.context.v1.DockerEndpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    host: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.context.v1.DockerEndpoint}
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.context.v1.DockerEndpoint;
  return proto.com.docker.api.protos.context.v1.DockerEndpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.context.v1.DockerEndpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.context.v1.DockerEndpoint}
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.context.v1.DockerEndpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.context.v1.DockerEndpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHost();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string host = 1;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint.prototype.getHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.DockerEndpoint} returns this
 */
proto.com.docker.api.protos.context.v1.DockerEndpoint.prototype.setHost = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.context.v1.AciEndpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.context.v1.AciEndpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    region: jspb.Message.getFieldWithDefault(msg, 1, ""),
    resourceGroup: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subscriptionId: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.context.v1.AciEndpoint}
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.context.v1.AciEndpoint;
  return proto.com.docker.api.protos.context.v1.AciEndpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.context.v1.AciEndpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.context.v1.AciEndpoint}
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRegion(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceGroup(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubscriptionId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.context.v1.AciEndpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.context.v1.AciEndpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRegion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getResourceGroup();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSubscriptionId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string region = 1;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.prototype.getRegion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.AciEndpoint} returns this
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.prototype.setRegion = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string resource_group = 2;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.prototype.getResourceGroup = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.AciEndpoint} returns this
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.prototype.setResourceGroup = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string subscription_id = 3;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.prototype.getSubscriptionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.AciEndpoint} returns this
 */
proto.com.docker.api.protos.context.v1.AciEndpoint.prototype.setSubscriptionId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.context.v1.EcsEndpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.context.v1.EcsEndpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    profile: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fromEnvironment: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.context.v1.EcsEndpoint}
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.context.v1.EcsEndpoint;
  return proto.com.docker.api.protos.context.v1.EcsEndpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.context.v1.EcsEndpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.context.v1.EcsEndpoint}
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfile(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFromEnvironment(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.context.v1.EcsEndpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.context.v1.EcsEndpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProfile();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFromEnvironment();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string profile = 1;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.prototype.getProfile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.EcsEndpoint} returns this
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.prototype.setProfile = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool from_environment = 2;
 * @return {boolean}
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.prototype.getFromEnvironment = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.com.docker.api.protos.context.v1.EcsEndpoint} returns this
 */
proto.com.docker.api.protos.context.v1.EcsEndpoint.prototype.setFromEnvironment = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.context.v1.SetCurrentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.context.v1.SetCurrentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.context.v1.SetCurrentRequest}
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.context.v1.SetCurrentRequest;
  return proto.com.docker.api.protos.context.v1.SetCurrentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.context.v1.SetCurrentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.context.v1.SetCurrentRequest}
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.context.v1.SetCurrentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.context.v1.SetCurrentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.context.v1.SetCurrentRequest} returns this
 */
proto.com.docker.api.protos.context.v1.SetCurrentRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.context.v1.SetCurrentResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.context.v1.SetCurrentResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.context.v1.SetCurrentResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.SetCurrentResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.context.v1.SetCurrentResponse}
 */
proto.com.docker.api.protos.context.v1.SetCurrentResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.context.v1.SetCurrentResponse;
  return proto.com.docker.api.protos.context.v1.SetCurrentResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.context.v1.SetCurrentResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.context.v1.SetCurrentResponse}
 */
proto.com.docker.api.protos.context.v1.SetCurrentResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.context.v1.SetCurrentResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.context.v1.SetCurrentResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.context.v1.SetCurrentResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.SetCurrentResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.context.v1.ListRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.context.v1.ListRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.context.v1.ListRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.ListRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.context.v1.ListRequest}
 */
proto.com.docker.api.protos.context.v1.ListRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.context.v1.ListRequest;
  return proto.com.docker.api.protos.context.v1.ListRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.context.v1.ListRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.context.v1.ListRequest}
 */
proto.com.docker.api.protos.context.v1.ListRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.context.v1.ListRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.context.v1.ListRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.context.v1.ListRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.ListRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.docker.api.protos.context.v1.ListResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.context.v1.ListResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.context.v1.ListResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.context.v1.ListResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.ListResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    contextsList: jspb.Message.toObjectList(msg.getContextsList(),
    proto.com.docker.api.protos.context.v1.Context.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.context.v1.ListResponse}
 */
proto.com.docker.api.protos.context.v1.ListResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.context.v1.ListResponse;
  return proto.com.docker.api.protos.context.v1.ListResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.context.v1.ListResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.context.v1.ListResponse}
 */
proto.com.docker.api.protos.context.v1.ListResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.docker.api.protos.context.v1.Context;
      reader.readMessage(value,proto.com.docker.api.protos.context.v1.Context.deserializeBinaryFromReader);
      msg.addContexts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.context.v1.ListResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.context.v1.ListResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.context.v1.ListResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.context.v1.ListResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getContextsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.docker.api.protos.context.v1.Context.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Context contexts = 1;
 * @return {!Array<!proto.com.docker.api.protos.context.v1.Context>}
 */
proto.com.docker.api.protos.context.v1.ListResponse.prototype.getContextsList = function() {
  return /** @type{!Array<!proto.com.docker.api.protos.context.v1.Context>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.docker.api.protos.context.v1.Context, 1));
};


/**
 * @param {!Array<!proto.com.docker.api.protos.context.v1.Context>} value
 * @return {!proto.com.docker.api.protos.context.v1.ListResponse} returns this
*/
proto.com.docker.api.protos.context.v1.ListResponse.prototype.setContextsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.docker.api.protos.context.v1.Context=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.docker.api.protos.context.v1.Context}
 */
proto.com.docker.api.protos.context.v1.ListResponse.prototype.addContexts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.docker.api.protos.context.v1.Context, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.docker.api.protos.context.v1.ListResponse} returns this
 */
proto.com.docker.api.protos.context.v1.ListResponse.prototype.clearContextsList = function() {
  return this.setContextsList([]);
};


goog.object.extend(exports, proto.com.docker.api.protos.context.v1);
