// source: compose/v1/compose.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.docker.api.protos.compose.v1.ComposeDownRequest', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.ComposeDownResponse', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.ComposeServicesRequest', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.ComposeServicesResponse', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.ComposeStacksRequest', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.ComposeStacksResponse', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.ComposeUpRequest', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.ComposeUpResponse', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.Service', null, global);
goog.exportSymbol('proto.com.docker.api.protos.compose.v1.Stack', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.docker.api.protos.compose.v1.ComposeUpRequest.repeatedFields_, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.ComposeUpRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.ComposeUpRequest.displayName = 'proto.com.docker.api.protos.compose.v1.ComposeUpRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.ComposeUpResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.ComposeUpResponse.displayName = 'proto.com.docker.api.protos.compose.v1.ComposeUpResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.docker.api.protos.compose.v1.ComposeDownRequest.repeatedFields_, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.ComposeDownRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.ComposeDownRequest.displayName = 'proto.com.docker.api.protos.compose.v1.ComposeDownRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.ComposeDownResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.ComposeDownResponse.displayName = 'proto.com.docker.api.protos.compose.v1.ComposeDownResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.ComposeStacksRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.displayName = 'proto.com.docker.api.protos.compose.v1.ComposeStacksRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.repeatedFields_, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.ComposeStacksResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.displayName = 'proto.com.docker.api.protos.compose.v1.ComposeStacksResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.Stack = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.Stack, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.Stack.displayName = 'proto.com.docker.api.protos.compose.v1.Stack';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.repeatedFields_, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.ComposeServicesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.displayName = 'proto.com.docker.api.protos.compose.v1.ComposeServicesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.repeatedFields_, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.ComposeServicesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.displayName = 'proto.com.docker.api.protos.compose.v1.ComposeServicesResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.docker.api.protos.compose.v1.Service = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.docker.api.protos.compose.v1.Service.repeatedFields_, null);
};
goog.inherits(proto.com.docker.api.protos.compose.v1.Service, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.com.docker.api.protos.compose.v1.Service.displayName = 'proto.com.docker.api.protos.compose.v1.Service';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.ComposeUpRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    workdir: jspb.Message.getFieldWithDefault(msg, 2, ""),
    filesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.ComposeUpRequest;
  return proto.com.docker.api.protos.compose.v1.ComposeUpRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkdir(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addFiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.ComposeUpRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWorkdir();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFilesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional string projectName = 1;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.getProjectname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.setProjectname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string workDir = 2;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.getWorkdir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.setWorkdir = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string files = 3;
 * @return {!Array<string>}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.getFilesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.setFilesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.addFiles = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeUpRequest.prototype.clearFilesList = function() {
  return this.setFilesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.ComposeUpResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeUpResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectname: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpResponse}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.ComposeUpResponse;
  return proto.com.docker.api.protos.compose.v1.ComposeUpResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeUpResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpResponse}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.ComposeUpResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeUpResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string projectName = 1;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse.prototype.getProjectname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeUpResponse} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeUpResponse.prototype.setProjectname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.ComposeDownRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    workdir: jspb.Message.getFieldWithDefault(msg, 2, ""),
    filesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.ComposeDownRequest;
  return proto.com.docker.api.protos.compose.v1.ComposeDownRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkdir(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addFiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.ComposeDownRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWorkdir();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFilesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional string projectName = 1;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.getProjectname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.setProjectname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string workDir = 2;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.getWorkdir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.setWorkdir = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string files = 3;
 * @return {!Array<string>}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.getFilesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.setFilesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.addFiles = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeDownRequest.prototype.clearFilesList = function() {
  return this.setFilesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.ComposeDownResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeDownResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectname: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownResponse}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.ComposeDownResponse;
  return proto.com.docker.api.protos.compose.v1.ComposeDownResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeDownResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownResponse}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectname(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.ComposeDownResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeDownResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string projectName = 1;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse.prototype.getProjectname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeDownResponse} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeDownResponse.prototype.setProjectname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeStacksRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    all: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeStacksRequest}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.ComposeStacksRequest;
  return proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeStacksRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeStacksRequest}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectname(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAll(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeStacksRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAll();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string projectName = 1;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.prototype.getProjectname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeStacksRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.prototype.setProjectname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool all = 2;
 * @return {boolean}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.prototype.getAll = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeStacksRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksRequest.prototype.setAll = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeStacksResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    stacksList: jspb.Message.toObjectList(msg.getStacksList(),
    proto.com.docker.api.protos.compose.v1.Stack.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeStacksResponse}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.ComposeStacksResponse;
  return proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeStacksResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeStacksResponse}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.docker.api.protos.compose.v1.Stack;
      reader.readMessage(value,proto.com.docker.api.protos.compose.v1.Stack.deserializeBinaryFromReader);
      msg.addStacks(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeStacksResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStacksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.docker.api.protos.compose.v1.Stack.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Stack stacks = 1;
 * @return {!Array<!proto.com.docker.api.protos.compose.v1.Stack>}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.prototype.getStacksList = function() {
  return /** @type{!Array<!proto.com.docker.api.protos.compose.v1.Stack>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.docker.api.protos.compose.v1.Stack, 1));
};


/**
 * @param {!Array<!proto.com.docker.api.protos.compose.v1.Stack>} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeStacksResponse} returns this
*/
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.prototype.setStacksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.docker.api.protos.compose.v1.Stack=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.docker.api.protos.compose.v1.Stack}
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.prototype.addStacks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.docker.api.protos.compose.v1.Stack, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeStacksResponse} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeStacksResponse.prototype.clearStacksList = function() {
  return this.setStacksList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.Stack.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.Stack} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.Stack.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    status: jspb.Message.getFieldWithDefault(msg, 3, ""),
    reason: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.Stack}
 */
proto.com.docker.api.protos.compose.v1.Stack.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.Stack;
  return proto.com.docker.api.protos.compose.v1.Stack.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.Stack} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.Stack}
 */
proto.com.docker.api.protos.compose.v1.Stack.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setReason(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.Stack.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.Stack} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.Stack.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getReason();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.Stack} returns this
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.Stack} returns this
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string status = 3;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.Stack} returns this
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string reason = 4;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.getReason = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.Stack} returns this
 */
proto.com.docker.api.protos.compose.v1.Stack.prototype.setReason = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectname: jspb.Message.getFieldWithDefault(msg, 1, ""),
    workdir: jspb.Message.getFieldWithDefault(msg, 2, ""),
    filesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.ComposeServicesRequest;
  return proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectname(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkdir(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addFiles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectname();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWorkdir();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFilesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
};


/**
 * optional string projectName = 1;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.getProjectname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.setProjectname = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string workDir = 2;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.getWorkdir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.setWorkdir = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string files = 3;
 * @return {!Array<string>}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.getFilesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.setFilesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.addFiles = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesRequest} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesRequest.prototype.clearFilesList = function() {
  return this.setFilesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeServicesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    servicesList: jspb.Message.toObjectList(msg.getServicesList(),
    proto.com.docker.api.protos.compose.v1.Service.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesResponse}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.ComposeServicesResponse;
  return proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeServicesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesResponse}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.docker.api.protos.compose.v1.Service;
      reader.readMessage(value,proto.com.docker.api.protos.compose.v1.Service.deserializeBinaryFromReader);
      msg.addServices(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.ComposeServicesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getServicesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.docker.api.protos.compose.v1.Service.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Service services = 1;
 * @return {!Array<!proto.com.docker.api.protos.compose.v1.Service>}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.prototype.getServicesList = function() {
  return /** @type{!Array<!proto.com.docker.api.protos.compose.v1.Service>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.docker.api.protos.compose.v1.Service, 1));
};


/**
 * @param {!Array<!proto.com.docker.api.protos.compose.v1.Service>} value
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesResponse} returns this
*/
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.prototype.setServicesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.docker.api.protos.compose.v1.Service=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.docker.api.protos.compose.v1.Service}
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.prototype.addServices = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.docker.api.protos.compose.v1.Service, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.docker.api.protos.compose.v1.ComposeServicesResponse} returns this
 */
proto.com.docker.api.protos.compose.v1.ComposeServicesResponse.prototype.clearServicesList = function() {
  return this.setServicesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.docker.api.protos.compose.v1.Service.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.toObject = function(opt_includeInstance) {
  return proto.com.docker.api.protos.compose.v1.Service.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.docker.api.protos.compose.v1.Service} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.Service.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    replicas: jspb.Message.getFieldWithDefault(msg, 3, 0),
    desired: jspb.Message.getFieldWithDefault(msg, 4, 0),
    portsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.docker.api.protos.compose.v1.Service}
 */
proto.com.docker.api.protos.compose.v1.Service.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.docker.api.protos.compose.v1.Service;
  return proto.com.docker.api.protos.compose.v1.Service.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.docker.api.protos.compose.v1.Service} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.docker.api.protos.compose.v1.Service}
 */
proto.com.docker.api.protos.compose.v1.Service.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setReplicas(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDesired(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addPorts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.docker.api.protos.compose.v1.Service.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.docker.api.protos.compose.v1.Service} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.docker.api.protos.compose.v1.Service.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getReplicas();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getDesired();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getPortsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.Service} returns this
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.com.docker.api.protos.compose.v1.Service} returns this
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 replicas = 3;
 * @return {number}
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.getReplicas = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.docker.api.protos.compose.v1.Service} returns this
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.setReplicas = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 desired = 4;
 * @return {number}
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.getDesired = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.com.docker.api.protos.compose.v1.Service} returns this
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.setDesired = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated string Ports = 5;
 * @return {!Array<string>}
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.getPortsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.com.docker.api.protos.compose.v1.Service} returns this
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.setPortsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.com.docker.api.protos.compose.v1.Service} returns this
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.addPorts = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.com.docker.api.protos.compose.v1.Service} returns this
 */
proto.com.docker.api.protos.compose.v1.Service.prototype.clearPortsList = function() {
  return this.setPortsList([]);
};


goog.object.extend(exports, proto.com.docker.api.protos.compose.v1);
